apiVersion: v1
kind: Namespace
metadata:
  name: task-manager
---
# ==========================================
# 1. Config & Secrets
# ==========================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: task-manager
data:
  NODE_ENV: "production"
  PORT: "3000"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: task-manager
type: Opaque
stringData:
  API_KEY: "killercoda-secret"
---
# ==========================================
# 2. Storage (HostPath for Kubeadm)
# ==========================================
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/tasks
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-data-pvc
  namespace: task-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# ==========================================
# 3. Backend (API)
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: task-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: api
        image: task-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: backend-config
        volumeMounts:
        - name: data
          mountPath: /app/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: backend-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: task-manager
spec:
  type: ClusterIP # Change to 'NodePort' to expose externally
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
    # nodePort: 30001 # Uncomment if changing type to NodePort
---
# ==========================================
# 4. Frontend (UI)
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: task-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: ui
        image: task-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
# ==========================================
# 5. Access (Service NodePort)
# ==========================================
# In KillerCoda, NodePorts (30000-32767) are usually exposed
apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
  namespace: task-manager
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080 
